apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - secrets.yaml
  #  - composition.yml
    - prometheus
    - jenkins
#    - cert-manager
#    - crossplane
    - argocd
    - ingress
#    - vault

#helmCharts:
#    - name: cert-manager
#      releaseName: my-cert-manager
#      namespace: cert-manager
#      repo: https://charts.bitnami.com/bitnami
#      includeCRDs: true

#namespace: argocd
#  - secrets.yml
#  - deployment.yml
#  - ../base
#  - servi

#namePrefix: demo
#nameSuffix: yuri
# custom index.html page
#configMapGenerator:
#    - name: nginx-cm
#      namespace: default
#      files:
#          - cm-index.html
#
## Bitnami NGINX helm chart
#helmChartInflationGenerator:
#    - chartName: nginx
#      chartRepoUrl: https://charts.bitnami.com/bitnami
#      chartVersion: 9.5.4
#      releaseName: my-nginx-release
#      releaseNamespace: nginx-chart
#        # override with these custom values
#      values: values.yaml