---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: crossplane
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://charts.crossplane.io/stable
# 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