apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
#    - ingress.yaml
namespace: prometheus
helmCharts:
    - name: prometheus
      repo: https://prometheus-community.github.io/helm-charts
      version: 15.10.5
      releaseName: my-prometheus
      namespace: prometheus
      includeCRDs: true
    - name: grafana
      repo: https://charts.bitnami.com/bitnami
      releaseName: my-grafana
      namespace: prometheus
      includeCRDs: true
#      valuesFile: values.yaml