apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
  labels:
    kubernetes.io/metadata.name: prometheus
#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: grafana
#  labels:
#    kubernetes.io/metadata.name: grafana

