# pre command
# ctlptl create registry ctlptl-registry --port=5005

#apiVersion:: ctlptl.dev/v1alpha1
#kind: Cluster
#product: docker-desktop
#minCPUs: 4
#---
#apiVersion: ctlptl.dev/v1alpha1
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
#  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
#registry: ctlptl-registry
#---
#apiVersion: ctlptl.dev/v1alpha1
#kind: Registry
#name: ctlptl-registry
#port: 5005
