apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
#  - secrets.yml
#  - deployment.yml
#  - ../base
#  - servi

#  - name: argo-cd
#    repo: https://charts.bitnami.com/bitnami
#    #    version: 15.10.5
#    releaseName: argo-workflows
#    namespace: argocd
#    includeCRDs: true
resources:
    - namespace.yml
#    - https://github.com/argoproj/argo-workflows/releases/download/v3.3.9/install.yaml
#    - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    #    - https://raw.githubusercontent.com/argoproj/argo-cd/v2.0.4/manifests/ha/install.yaml
    - apps.yaml
#    - ingress.yaml
helmCharts:
    - name: argo-cd
      repo: https://charts.bitnami.com/bitnami
      version: 5.10.6
      releaseName: argo-cd
      namespace: argocd
      includeCRDs: true
      valuesFile: values.yaml
#      valuesInline:
#        server:
#          ingress: true
#namePrefix: demo
#nameSuffix: yuri
