apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-workflows

resources:
    - namespace.yml
    - https://github.com/argoproj/argo-workflows/releases/download/v3.3.9/install.yaml

