apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml

helmCharts:
  - name: jenkins
    repo: https://charts.bitnami.com/bitnami
    releaseName: jenkins
    namespace: jenkins
    includeCRDs: true
    valuesFile: values.yaml

