apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
#    - ingress.yaml
namespace: vault
helmCharts:
    - name: vault
      repo: https://helm.releases.hashicorp.com
      version: 0.20.1
      releaseName: my-vault
      namespace: vault
      includeCRDs: true
