apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml

helmCharts:
  - name: nginx-ingress-controller
    repo: https://charts.bitnami.com/bitnami
    releaseName: ingress-nginx
    namespace: ingress-nginx
    includeCRDs: true

