---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-commands
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yurikrupnik/go-commands.git
    targetRevision: HEAD
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: go-commands

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true