---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-commands
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yurikrupnik/go-commands.git
    targetRevision: HEAD
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: go-commands

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
---

#apiVersion: generators.external-secrets.io/v1alpha1
#kind: GCRAccessToken
#metadata:
#  name: gcr-gen
#spec:
#  projectID: "devops-386509"
#  # choose authentication strategy
#  auth:
#    # option 2: GCP service account
##    secretRef:
##      secretAccessKeySecretRef:
##        name: secret-puller              # secret name containing SA key
##        key: creds
##    # option 1: workload identity
#    workloadIdentity:
#      # point to the workload identity
#      # service account
#      serviceAccountRef:
#        name: ""
##        audiences: []
#      # the cluster can live in a different project or location
#      # use the following fields to configure where the cluster lives
#      clusterLocation: ""
#      clusterName: ""
#      clusterProjectID: "devops-386509"


